# Recoger Project Definition

id: recoger
name: Recoger
version: "0.1.0"

# =============================================================================
# IDENTITY
# =============================================================================

brand:
  spanish_meaning: "to collect, gather"
  tagline: "Continuous collection of security posture"
  positioning: "Endpoint security and device compliance platform"
  parent: KomplyOne
  endorsement: "A KomplyOne Company"

domains:
  primary: recoger.co
  alternatives:
    - recoger.io
    - getrecoger.com

# =============================================================================
# STATUS
# =============================================================================

status: active
priority: primary
phase: development  # concept | development | beta | production | maintenance

milestones:
  - name: "Desktop agent MVP"
    status: in_progress
    target: "2026-Q1"
  - name: "API and dashboard"
    status: planned
    target: "2026-Q1"
  - name: "Public launch"
    status: planned
    target: "2026-Q2"

# =============================================================================
# COMPONENTS
# =============================================================================

components:
  desktop:
    name: "Recoger Desktop"
    description: "Cross-platform desktop agent"
    status: in_progress
    repo: recoger-desktop
    tech:
      framework: tauri-2.0
      backend: rust
      frontend: [react, typescript]
      styling: tailwindcss
    platforms: [macos, windows, linux]
    
  api:
    name: "Recoger API"
    description: "Multi-tenant SaaS backend"
    status: in_progress
    repo: recoger-srv
    tech:
      framework: fastapi
      language: python
      database: postgresql
      cache: redis
      
  mobile:
    name: "Recoger Mobile"
    description: "Companion mobile app"
    status: planned
    repo: recoger-mobile
    tech:
      framework: flutter
      language: dart
    platforms: [ios, android]
    
  web:
    name: "Recoger Dashboard"
    description: "Admin web interface"
    status: in_progress
    repo: recoger-srv  # Part of srv repo
    tech:
      framework: react
      language: typescript
      styling: [tailwindcss, shadcn-ui]

  website:
    name: "Recoger Website"
    description: "Marketing website"
    status: in_progress
    repo: recoger-website
    tech:
      framework: astro
      styling: [tailwindcss, react]
    hosting: cloudflare-pages

# =============================================================================
# BUDGET
# =============================================================================

budget:
  category: commercial
  monthly_limit: 200  # EUR
  cost_priority: moderate  # aggressive | moderate | relaxed
  notes: "Pre-revenue. Minimize costs but don't compromise on EU hosting or security."
  
  preferences:
    hosting:
      prefer: [hetzner, cloudflare]
      avoid: [aws, azure, gcp]
      exceptions: "Neon (PostgreSQL) and Redis Cloud (Frankfurt) are approved"
    services:
      prefer_free_tier: true
      accept_paid_for: [core-infrastructure, security, monitoring]
      avoid_paid_for: [nice-to-have-features]
      
  alerts:
    warn_before_paid_service: true
    warn_threshold: 50  # EUR/month for new services

# =============================================================================
# INFRASTRUCTURE
# =============================================================================

infrastructure:
  compute: hetzner
  database: neon
  cache: redis-cloud
  storage: cloudflare-r2
  cdn: cloudflare
  email: mailjet
  monitoring: betterstack
  errors: sentry
  
  regions:
    primary: frankfurt
    requirement: eu-only

# =============================================================================
# TARGET MARKET
# =============================================================================

market:
  segment: "Security-conscious SMBs"
  size: "10-500 employees"
  geography: "Europe (initial)"
  
  ideal_customer:
    - "Companies without dedicated security teams"
    - "Startups preparing for ISO 27001 or SOC 2"
    - "Companies with remote/hybrid workforce"
    
  pricing:
    model: per-device-monthly
    tiers:
      free:
        price: 0
        users: 10
        devices: 20
        note: "Manual tracking only"
      startup:
        price: 2  # EUR per device
        users: unlimited
        devices: unlimited
        note: "With agents"
      scaleup:
        price: 4  # EUR per device
        users: unlimited
        devices: unlimited
        note: "Full features"

# =============================================================================
# TECHNICAL CONTEXT
# =============================================================================

tech_stack:
  desktop: [rust, tauri, react, typescript, tailwindcss]
  api: [python, fastapi, sqlalchemy, postgresql, redis]
  mobile: [dart, flutter]
  web: [react, typescript, tailwindcss, shadcn-ui, tanstack-query]
  website: [astro, react, typescript, tailwindcss]

security:
  profile: high
  requirements:
    - "Multi-tenant isolation at all layers"
    - "EU data residency"
    - "Encryption at rest and in transit"
    - "SOC 2 Type II preparation"
  guidelines: "SECURE_DEVELOPMENT_INSTRUCTIONS_V4.md"

# =============================================================================
# RELATED FILES
# =============================================================================

files:
  context: context.md
  components:
    desktop: components/desktop.md
    api: components/api.md
    mobile: components/mobile.md
    website: components/website.md
  state:
    tasks: state/tasks.md
    decisions: state/decisions.md
  docs:
    deployment: "../../recoger-srv/docs/DEPLOYMENT_PLAN.md"
    infrastructure: "../../recoger-srv/docs/INFRASTRUCTURE_REFERENCE.md"
